### ISSUE TITLE
[ :sparkles: ] - New routes only with patients/devices enabled

### ISSUE THREAD

**Issue by bartyo** [ProjSante/webapp#24]
Routes api/relays with a GET answer respond all patients and all measure for each patient.
Data is too big to be processed with a small chip.

Is it possible to create a new routes with only patients/devices _id **enabled** as response.
Like this : 
```json
[
  {
     "_id":"5d9c497fecff920017af169e"
  },
  {
     "_id":"5d9c197fgcfd927017af15ea"
  },
]

**Comment by bartyo** [comment]
Routes will be api/relays/devices. GET to get all devices enabled and ``POST:{"_id":"5d9c497fecff920017af169e"}`` which return status 200 if device **is enabled** or status 404 if device **is not enabled**

**Comment by Kmelow** [comment]
> ... and `POST:{"_id":"5d9c497fecff920017af169e"}` which return status 200 if device **is enabled** or status 404 if device **is not enabled**

Moved to issue #34

**Comment by Kmelow** [comment]
Done. Now you can make **GET** `api/relays/devices`
